QUESTION1

In [1]:
import numpy as np
arr = np.arange(2, 50, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


QUESTION2

In [2]:
# importing numpy with alias name
import numpy as np

# creating a 2 empty list:
lst_1 = []
lst_2 = []

# getting values for lst_1 from user:
for i in range(5):
  x=int(input("\nEnter the value for lst_1 : "))
  lst_1.append(x)

# getting values for lst_2 from user:
for i in range(5):
  x=int(input("\nEnter the value for lst_2 : "))
  lst_2.append(x)

# converting list into array:
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

# concatenating 2 array:
arr = np.concatenate((arr_1, arr_2))
print("\nArray value for concatenated arr :",arr)

# sorting up concatenated array
sortArr = np.sort(arr)
print("\nSorted Array for concatenated arr :",sortArr)


Enter the value for lst_1 : 5

Enter the value for lst_1 : 2

Enter the value for lst_1 : 3

Enter the value for lst_1 : 4

Enter the value for lst_1 : 2

Enter the value for lst_2 : 7

Enter the value for lst_2 : 8

Enter the value for lst_2 : 9

Enter the value for lst_2 : 4

Enter the value for lst_2 : 5

Array value for concatenated arr : [5 2 3 4 2 7 8 9 4 5]

Sorted Array for concatenated arr : [2 2 3 4 4 5 5 7 8 9]


QUESTION3

In [3]:
import numpy as np
arr = np.array([[4,2,2],[8,9,5]])
print("\nDimensions in array : ", arr.ndim)
print("\nSize of array : ", arr.size)


Dimensions in array :  2

Size of array :  6


QUESTION4

In [5]:
import numpy as np
arr = np.arange(20)
print("\nShape of Array :",arr.shape)
row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)


Shape of Array : (20,)

Shape of 2d Array in row major : (1, 20)

Shape of 2d Array in column major : (20, 1)


QUESTION5

In [6]:
import numpy as np
arr_1 = np.square([6, 5, 4, 3, 2])
arr_2 = np.square([9, 8, 7, 6, 5])
print("\nHorizontal Append :", np.hstack((arr_1, arr_2)))
print("\nVertical Append :", np.vstack((arr_1, arr_2)))


Horizontal Append : [36 25 16  9  4 81 64 49 36 25]

Vertical Append : [[36 25 16  9  4]
 [81 64 49 36 25]]


QUESTION6

In [7]:
import numpy as np
arr_1 = np.array([1, 5, 9, 10, 8, 1, 4, 2, 3, 3, 6, 6, 5, 7, 8, 11])
unique, counts = np.unique(arr_1, return_counts=True)
arr = np.asarray((unique, counts)).T
print(arr)

[[ 1  2]
 [ 2  1]
 [ 3  2]
 [ 4  1]
 [ 5  2]
 [ 6  2]
 [ 7  1]
 [ 8  2]
 [ 9  1]
 [10  1]
 [11  1]]
